server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root2
    password: root2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: RATING-SERVICES
  config:
    import: optional:configserver://localhost::8085